export { default as Avax } from "./avax.png";
export { default as Bnb } from "./bnb.png";
export { default as Pixp } from "./pixp.png";
export { default as PixpLogo } from "./pixp_logo.png";
export { default as Solana } from "./solana.png";
export { default as Tusd } from "./tusd.png";
export { default as Usdc } from "./usdc.png";
export { default as Xrp } from "./xrp.png";
export { default as Usdt } from "./usdt.png";
export { default as CCD } from "./ccd.png";
export { default as KAVA } from "./kava.png";
export { default as etherium } from "./eth.png";
export { default as addIcon } from "./icon_add.png";
export { default as iconEquals } from "./icon _equal_.png";
export { default as iconRefresh } from "./icon_refresh.png";
